openapi: 3.0.0

info:
  title: VPMC API
  description: vpmc RESTful API in Node.js with TypeScript.

servers:
  - url: http://localhost:9085/api
    description: Testing local server
  - url: http://140.122.82.98:9085/api
    description: Production server

paths:

  /Auth/authenticate:
    post:
      tags: 
        - Auth
      summary: 使用者驗證.
      consumes:
        - application/x-www-form-urlencoded
      description: 於登入時使用
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:

                email:
                  required: true
                  default: jim60308@gmail.com
                  type: string
                  description: 電子郵件
                
                password:
                  required: true
                  default: T3iSQkjwLFooeeqWQpY9OFEuMTaaKVzGC81jpYcMRqc=
                  type: string
                  description: 密碼
      responses:
        '200':    # status code
          description: accessToken
          content:
            application/json:
              schema: 
                type: object

  /Commitee/listTownAvg:
    get:
      tags: 
        - Commitee
      summary: 查詢鄉鎮市區單位價格(元/平方公尺).
      description: 現在只有新北市10年份的資料
      parameters:

        - in: query
          name: county
          required: true
          default: 新北市
          schema:
            type: string
          description: 縣市

        - in: query
          name: town
          required: true
          default: 林口區
          schema:
            type: string
          description: 鄉鎮市區

        - in: query
          name: startDate
          required: true
          default: 2021-01-01
          schema:
            type: string
          description: yyyy-mm-dd

        - in: query
          name: endDate
          required: true
          default: 2022-01-01
          schema:
            type: string
          description: yyyy-mm-dd

      responses:
        '200':    # status code
          description: 該鄉鎮的單位均價
          content:
            application/json:
              schema: 
                type: object
  
  /Commitee/listCommiteeByExtent:
    get:
      tags: 
        - Commitee
      summary: 列出方框範圍內的基本管委會資料.
      description: 現在只有新北市10年份的資料
      parameters:

        - in: query
          name: xmin
          required: true
          default: 121.45344870570658
          schema:
            type: number
          description: 最小經度

        - in: query
          name: ymin
          required: true
          default: 25.004733928174055
          schema:
            type: number
          description: 最小緯度

        - in: query
          name: xmax
          required: true
          default: 121.4697565351926
          schema:
            type: number
          description: 最大經度
        
        - in: query
          name: ymax
          required: true
          default: 25.012356721844185
          schema:
            type: number
          description: 最大緯度

      responses:
        '200':    # status code
          description: 範圍內的所有社區資料
          content:
            application/json:
              schema: 
                type: array
    
  /Commitee/getSimpleInfo:
    get:
      tags: 
        - Commitee
      summary: 查詢社區半徑範圍內的實價交易數量、完工日期、建物型態、平均單位價格(元/平方公尺).
      description: 現在只有新北市10年份的資料
      parameters:

        - in: query
          name: commiteeId
          required: true
          default: 836bf30d-e426-49df-856f-ffb05eef7d5d
          schema:
            type: string
          description: 管委會id

        - in: query
          name: bufferRadius
          required: true
          default: 35
          schema:
            type: number
          description: 搜尋半徑

      responses:
        '200':    # status code
          description: 該社區半徑範圍內的實價交易數量、完工日期、建物型態、平均單位價格(元/平方公尺).
          content:
            application/json:
              schema: 
                type: object
  
  /Commitee/getAprInfo:
    get:
      tags: 
        - Commitee
      summary: 用管委會id查詢實價登陸交易紀錄.
      description: 現在只有新北市10年份的資料
      parameters:

        - in: query
          name: commiteeId
          required: true
          default: 52daa333-6e71-4dfd-a70d-97e7dd0cde2d
          schema:
            type: string
          description: 管委會id

      responses:
        '200':    # status code
          description: 該社區的所有實價登陸交易紀錄.
          content:
            application/json:
              schema: 
                type: object

  /Apr/getTownInfo:
    get:
      tags: 
        - Apr
      summary: 查詢鄉鎮市區的實價登陸資料，並且計算統計結果.
      description: 注意! 有些區的資料量過大，所以在swagger上會一直轉圈。
      parameters:

        - in: query
          name: county
          required: true
          default: 新北市
          schema:
            type: string
          description: 縣市

        - in: query
          name: town
          required: true
          default: 金山區
          schema:
            type: string
          description: 鄉鎮市區

      responses:
        '200':    # status code
          description: 該行政區的實價登陸資料，依照建物型態與交易年分計算統計結果.
          content:
            application/json:
              schema: 
                type: object