openapi: 3.0.0

info:
  title: VPMC API
  description: vpmc RESTful API in Node.js with TypeScript.
  version: 0.1.9

servers:
  - url: http://localhost:9085/api
    description: Testing local server

paths:
  /Commitee/listTownAvg:
    get:
      tags: 
        - Commitee
      summary: 查詢鄉鎮市區單位價格(元/平方公尺).
      description: Optional extended description in CommonMark or HTML.
      parameters:
        - in: query
          name: county
          schema:
            type: string
          description: 縣市
        - in: query
          name: town
          schema:
            type: string
          description: 鄉鎮市區
        - in: query
          name: startDate
          schema:
            type: string
          description: yyyy-mm-dd
        - in: query
          name: endDate
          schema:
            type: string
          description: yyyy-mm-dd
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string